"""srapi — Python client for the speedrun.com REST API v1."""

from .client import Client
from .collection import Collection
from .errors import SrapiError
from .types import AssetLink, Duration, Link
from .resources import (
    Category,
    Developer,
    Engine,
    Game,
    GameRuleset,
    GameType,
    Genre,
    Guest,
    Leaderboard,
    LeaderboardEntry,
    Level,
    Notification,
    NotificationItem,
    PersonalBest,
    Platform,
    PlayerRule,
    Publisher,
    Region,
    Run,
    RunPlayer,
    RunStatus,
    RunSystem,
    RunTimes,
    RunVideo,
    Series,
    User,
    UserLocation,
    UserNameStyle,
    Variable,
    VariableScope,
    VariableValue,
)

__all__ = [
    "Client",
    "Collection",
    "SrapiError",
    "AssetLink", "Duration", "Link",
    "Category", "PlayerRule",
    "Developer", "Engine", "GameType", "Genre", "Publisher",
    "Game", "GameRuleset",
    "Guest",
    "Leaderboard", "LeaderboardEntry",
    "Level",
    "Notification", "NotificationItem",
    "PersonalBest",
    "Platform",
    "Region",
    "Run", "RunPlayer", "RunStatus", "RunSystem", "RunTimes", "RunVideo",
    "Series",
    "User", "UserLocation", "UserNameStyle",
    "Variable", "VariableScope", "VariableValue",
]
